# Site settings
title: Wei's Blog
email: meow@15926.tech
description: > # this means to ignore newlines until "baseurl:"
  Wei's Blog
baseurl: "https://15926.tech" # the subpath of your site, e.g. /blog/
url: https://15926.tech # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Wei He

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 500

# Social account
twitter: 
weibo: 
github: 
instagram: 
linkedin: 

# avatar and Favicon
avatar: /assets/icon/site-avatar.png
#这里填写图片地址
favicon: /assets/icon/site-avatar.png
#这里填写图片地址

# disqus config
# disqus:
#  shortname: 

# google analytics config
# ga:
#  id: UA-54767140-1
#  url: 

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

